import { Quiz } from "@/types/api/quizzes";

export const quizzes: Quiz[] = [
  {
    uuid: "quiz-001",
    title: "Základy TypeScriptu",
    attemptsCount: 3,
    created_at: "2025-01-01T10:00:00Z",
    updated_at: "2025-01-02T10:00:00Z",
    updateCount: 1,
    questions: [
      {
        uuid: "q-001-1",
        type: "singleChoice",
        question: "Co je TypeScript?",
        options: [
          "Framework",
          "Nadstavba JavaScriptu",
          "Databáze",
          "Operační systém",
        ],
        correctIndex: 1,
      },
      {
        uuid: "q-001-2",
        type: "multipleChoice",
        question: "Jaké typy TypeScript podporuje?",
        options: ["string", "number", "boolean", "table"],
        correctIndices: [0, 1, 2],
      },
    ],
  },
  {
    uuid: "quiz-002",
    title: "JavaScript – základy",
    attemptsCount: 5,
    created_at: "2025-01-03T09:00:00Z",
    updated_at: "2025-01-03T09:00:00Z",
    updateCount: 0,
    questions: [
      {
        uuid: "q-002-1",
        type: "singleChoice",
        question: "Které klíčové slovo deklaruje konstantu?",
        options: ["var", "let", "const", "static"],
        correctIndex: 2,
      },
      {
        uuid: "q-002-2",
        type: "multipleChoice",
        question: "Které jsou primitivní typy v JS?",
        options: ["string", "number", "object", "boolean"],
        correctIndices: [0, 1, 3],
      },
    ],
  },
  {
    uuid: "quiz-003",
    title: "HTML",
    attemptsCount: 2,
    created_at: "2025-01-04T08:00:00Z",
    updated_at: "2025-01-04T08:00:00Z",
    updateCount: 0,
    questions: [
      {
        uuid: "q-003-1",
        type: "singleChoice",
        question: "K čemu slouží HTML?",
        options: [
          "Stylování",
          "Struktura stránky",
          "Logika aplikace",
          "Databáze",
        ],
        correctIndex: 1,
      },
      {
        uuid: "q-003-2",
        type: "multipleChoice",
        question: "Které tagy jsou sémantické?",
        options: ["header", "footer", "div", "article"],
        correctIndices: [0, 1, 3],
      },
    ],
  },
  {
    uuid: "quiz-004",
    title: "CSS",
    attemptsCount: 4,
    created_at: "2025-01-05T11:00:00Z",
    updated_at: "2025-01-06T11:00:00Z",
    updateCount: 1,
    questions: [
      {
        uuid: "q-004-1",
        type: "singleChoice",
        question: "Která vlastnost mění barvu textu?",
        options: ["background", "font-style", "color", "display"],
        correctIndex: 2,
      },
      {
        uuid: "q-004-2",
        type: "multipleChoice",
        question: "Které jednotky jsou relativní?",
        options: ["px", "em", "rem", "%"],
        correctIndices: [1, 2, 3],
      },
    ],
  },
  {
    uuid: "quiz-005",
    title: "React – základy",
    attemptsCount: 6,
    created_at: "2025-01-06T12:00:00Z",
    updated_at: "2025-01-08T12:00:00Z",
    updateCount: 2,
    questions: [
      {
        uuid: "q-005-1",
        type: "singleChoice",
        question: "Co je React?",
        options: ["Framework", "Knihovna", "Programovací jazyk", "Databáze"],
        correctIndex: 1,
      },
      {
        uuid: "q-005-2",
        type: "multipleChoice",
        question: "Co patří do Reactu?",
        options: ["component", "state", "props", "router"],
        correctIndices: [0, 1, 2],
      },
    ],
  },
  {
    uuid: "quiz-006",
    title: "Backend",
    attemptsCount: 1,
    created_at: "2025-01-07T10:00:00Z",
    updated_at: "2025-01-07T10:00:00Z",
    updateCount: 0,
    questions: [
      {
        uuid: "q-006-1",
        type: "singleChoice",
        question: "Co je backend?",
        options: ["UI", "Serverová logika", "Design", "Mobilní aplikace"],
        correctIndex: 1,
      },
    ],
  },
  {
    uuid: "quiz-007",
    title: "Databáze",
    attemptsCount: 8,
    created_at: "2025-01-08T09:30:00Z",
    updated_at: "2025-01-09T09:30:00Z",
    updateCount: 1,
    questions: [
      {
        uuid: "q-007-1",
        type: "singleChoice",
        question: "Co je SQL?",
        options: ["Framework", "Dotazovací jazyk", "Datový typ", "Server"],
        correctIndex: 1,
      },
      {
        uuid: "q-007-2",
        type: "multipleChoice",
        question: "Které DB jsou relační?",
        options: ["PostgreSQL", "MongoDB", "MySQL", "SQLite"],
        correctIndices: [0, 2, 3],
      },
    ],
  },
  {
    uuid: "quiz-008",
    title: "Git",
    attemptsCount: 10,
    created_at: "2025-01-09T14:00:00Z",
    updated_at: "2025-01-10T14:00:00Z",
    updateCount: 1,
    questions: [
      {
        uuid: "q-008-1",
        type: "singleChoice",
        question: "K čemu slouží Git?",
        options: ["Testování", "Verzování kódu", "Build", "Deployment"],
        correctIndex: 1,
      },
    ],
  },
  {
    uuid: "quiz-009",
    title: "Bezpečnost webu",
    attemptsCount: 0,
    created_at: "2025-01-10T08:00:00Z",
    updated_at: "2025-01-10T08:00:00Z",
    updateCount: 0,
    questions: [
      {
        uuid: "q-009-1",
        type: "multipleChoice",
        question: "Které jsou webové útoky?",
        options: ["XSS", "SQL Injection", "DDoS", "MITM"],
        correctIndices: [0, 1, 2, 3],
      },
    ],
  },
  {
    uuid: "quiz-010",
    title: "Algoritmy",
    attemptsCount: 12,
    created_at: "2025-01-11T10:00:00Z",
    updated_at: "2025-01-12T10:00:00Z",
    updateCount: 2,
    questions: [
      {
        uuid: "q-010-1",
        type: "singleChoice",
        question: "Co je algoritmus?",
        options: [
          "Databáze",
          "Postup řešení problému",
          "Framework",
          "Programovací jazyk",
        ],
        correctIndex: 1,
      },
    ],
  },
];
